servers:
  first:
    item:
      slot: 13
      type: 'diamond_sword'
      name: '&cHardcore Factions'
      lore:
        - '&bOnline: &a{online}'
        - '&bSlots: &a{slots}'
        - '&bIn Queue: &a{queue}'
    
selector:
  item: compass
  name: '&aServer Selector &b(Right Click)'
pearl:
  item: stick
  name: '&aTeleporter &b(Right Click)'
shop:
  item: book
  name: '&aServer Shop &b(Right Click)'